#' Initialize input vectors for the ACMTF algorithm
#'
#' @param Z List object as generated by [setupCMTFdata()].
#' @param numComponents Integer stating the number of desired components for the CMTF model.
#' @param initialization Initialization method, either "random" or "nvec" (default "random"). Random will initialize random input vectors. Nvec will initialize vectors according to an singular value decomposition of the (matricized, if needed) concatenated datasets per mode.
#' @param output How to return output: as a "Fac" object (default) or vectorized ("vect").
#'
#' @return List or vector of initialized input vectors per mode.
#' @export
#'
#' @examples
#' I = 108                             # subject mode
#' J = 100                             # feature mode
#' K = 10                              # condition mode
#'
#' df = array(rnorm(I*J*K), c(I,J,K))  # Create the data
#' datasets = list(df, df)             # Two hypothetical data blocks
#' modes = list(c(1,2,3), c(1,4,5))    # Shared subject mode, feature and time modes separate
#' Z = setupCMTFdata(datasets, modes)
#' initializeACMTF(Z, 1)
initializeACMTF = function(Z, numComponents, initialization="random", output="Fac"){

  numModes = max(unlist(Z$modes))
  numDatasets = length(Z$object)
  init = initializeCMTF(Z, numComponents, initialization, output="Fac")

  # Normalize the initialized values to norm 1
  newInit = list()
  for(i in 1:numModes){
    newInit[[i]] = array(0L, dim(init[[i]]))
    for(j in 1:numComponents){
      newInit[[i]][,j] = init[[i]][,j] / rTensor::fnorm(rTensor::as.tensor(init[[i]][,j]))
    }
  }
  init = newInit

  # Initialize lambdas values as 1
  init[[numModes+1]] = array(1, c(numDatasets,numComponents))

  if(output=="vect"){
    return(fac_to_vect(init))
  }
  else{
    return(init)
  }
}
