#' Initialize input vectors for the CMTF algorithm
#'
#' @param Z List object as generated by [setupCMTFdata()].
#' @param numComponents Integer stating the number of desired components for the CMTF model.
#' @param initialization Initialization method, either "random" or "nvec" (default "random"). Random will initialize random input vectors. Nvec will initialize vectors according to an singular value decomposition of the (matricized, if needed) concatenated datasets per mode.
#' @param output How to return output: as a "Fac" object (default) or vectorized ("vect").
#'
#' @return List or vector of initialized input vectors per mode.
#' @export
#'
#' @examples
#' I = 108                             # subject mode
#' J = 100                             # feature mode
#' K = 10                              # condition mode
#'
#' df = array(rnorm(I*J*K), c(I,J,K))  # Create the data
#' datasets = list(df, df)             # Two hypothetical data blocks
#' modes = list(c(1,2,3), c(1,4,5))    # Shared subject mode, feature and time modes separate
#' Z = setupCMTFdata(datasets, modes)
#' initializeCMTF(Z, 1)
initializeCMTF = function(Z, numComponents, initialization="random", output="Fac"){

  init = list()
  numModes = max(unlist(Z$modes))
  numDatasets = length(Z$object)

  if(initialization == "random"){
    for(i in 1:numModes){
      size = Z$sizes[i]
      init[[i]] = array(stats::rnorm(size*numComponents), c(size, numComponents))
    }
  } else if(initialization == "nvec"){

    for(i in 1:numModes){
      eligibleDatasets = list()
      iterator = 1
      size = Z$sizes[i]

      for(p in 1:numDatasets){
        if(i %in% Z$modes[[p]]){
          eligibleDatasets[[iterator]] = rTensor::k_unfold(Z$object[[p]], which(Z$modes[[p]] == i))@data
          iterator = iterator + 1
        }
      }

      df = do.call(cbind, eligibleDatasets)
      init[[i]] = svd(df, numComponents)$u
    }
  }

  if(output=="vect"){
    return(fac_to_vect(init))
  }
  else{
    return(init)
  }
}
